# Generated by Django 3.2.7 on 2021-09-10 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_agegroupcontacts_agegroupcontact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agegroupcontact',
            old_name='email',
            new_name='user_email',
        ),
    ]
