# Generated by Django 3.2.7 on 2021-09-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_email_agegroupcontact_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agegroupcontact',
            name='photo',
            field=models.ImageField(null=True, upload_to='website/images'),
        ),
    ]
