# Generated by Django 3.2.7 on 2021-09-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_agegroupcontact_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agegroupcontact',
            name='photo',
            field=models.ImageField(null=True, upload_to='uploads/images'),
        ),
    ]
