# Generated by Django 3.2.7 on 2021-09-10 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_agegroupcontact_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglistaddress',
            name='mailing_list',
        ),
        migrations.AddField(
            model_name='mailinglistaddress',
            name='list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.team'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MailingList',
        ),
    ]
