# Generated by Django 3.2.7 on 2021-09-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20210910_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agegroupdownload',
            name='file',
            field=models.FileField(upload_to='uploads'),
        ),
    ]
