# Generated by Django 3.2.7 on 2021-09-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_agegroupdownload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agegroupdownload',
            name='file',
            field=models.FileField(upload_to='uploads/files'),
        ),
    ]
