# Generated by Django 3.2.7 on 2021-09-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_agegroupdownload_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agegroupcontact',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='agegroupdownload',
            name='downloadable_file',
            field=models.FileField(upload_to=''),
        ),
    ]
