# Generated by Django 3.2.7 on 2021-09-12 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20210912_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.team'),
            preserve_default=False,
        ),
    ]
