# Generated by Django 3.2.7 on 2021-09-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_welcomemessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='mail',
        ),
        migrations.AddField(
            model_name='contact',
            name='description',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='contact',
            name='position',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='primary',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='user_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
