# Generated by Django 3.2.7 on 2021-09-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20210914_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloadable_file', models.FileField(upload_to='downloadables/')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
