# Generated by Django 3.2.7 on 2021-09-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_download'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('description', models.TextField(max_length=10000)),
            ],
        ),
    ]
