# Generated by Django 3.2.7 on 2021-09-14 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
