# Generated by Django 3.2.7 on 2021-09-24 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_auto_20210914_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date_time',
            new_name='start_time',
        ),
    ]
