# Generated by Django 3.2.7 on 2021-09-24 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='receiver',
        ),
        migrations.AddField(
            model_name='mail',
            name='receivers',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.team'),
            preserve_default=False,
        ),
    ]
