# Generated by Django 3.2.7 on 2021-10-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_mailinglistaddress_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglistaddress',
            name='child',
            field=models.CharField(max_length=200),
        ),
    ]
