# Generated by Django 3.2.7 on 2021-10-05 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_alter_mailinglistaddress_child'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PitchDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.pitch')),
            ],
        ),
        migrations.CreateModel(
            name='PitchTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('pitch_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.pitchdate')),
            ],
        ),
    ]
