# Generated by Django 3.2.7 on 2021-10-05 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_pitch_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchtime',
            name='ref',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pitchtime',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.team'),
            preserve_default=False,
        ),
    ]
