# Generated by Django 3.2.7 on 2021-10-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_alter_pitchtime_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='agegroupnews',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='news',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
