# Generated by Django 3.2.7 on 2021-10-05 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_auto_20211005_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agegroupnews',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='news',
            name='photo',
        ),
        migrations.CreateModel(
            name='NewsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='images/')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.agegroupnews')),
            ],
        ),
    ]
