# Generated by Django 3.2.7 on 2021-10-05 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_auto_20211005_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsphoto',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.news'),
        ),
        migrations.CreateModel(
            name='AgeGroupNewsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='images/')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.agegroupnews')),
            ],
        ),
    ]
