# Generated by Django 3.2.8 on 2021-10-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_aboutpage_ethospage_tgastropage_welfarepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
