# Generated by Django 3.2.8 on 2021-10-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_welcomeimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WelcomeImage',
        ),
        migrations.AddField(
            model_name='welcomemessage',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
